### ISSUE TITLE
Access-Control-Allow-Origin is not working in Symphony 2.5.2

### ISSUE THREAD

**Issue by axpro** [michael-e/http_response_header_mappings#2]
It may be related to this: https://github.com/symphonycms/symphony-2/wiki/Migration-Guide-to-2.4-for-Developers#security

If I comment this out it works: https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/class.frontendpage.php#L248-L250

Thanks

**Comment by michael-e** [comment]
Can you be a bit more precise? What do you mean by "not working"? Do you attempt to override Symphony's header?

**Comment by axpro** [comment]
I'm trying to set Access-Control-Allow-Origin: * on a specific page and it's not working. If I comment the above code out it's working. Other arbitrary headers work.

**Comment by michael-e** [comment]
Since the extension uses Symphony's native method to set the headers, it's either a bug or an intended feature in Symphony. I will take a look.

**Comment by axpro** [comment]
[addHeaderToPage](http://www.getsymphony.com/learn/api/2.5.2/toolkit/page/#addHeaderToPage) expects 2 parameters: `key` and `value`. The extension ads `Access-Control-Allow-Origin: *` as a key so `class.frontpage.php` can't find the `access-control-allow-origin` key because it doesn't exist. The key added by the extension includes the value and is named: `access-control-allow-origin: *`

Thanks :)

**Comment by michael-e** [comment]
According to the [W3C](http://www.w3.org/TR/2008/WD-access-control-20080912/#access-control-allow-origin), the header is called `Access-Control-Allow-Origin`. Why do you attempt to set it in lowercase?

Anyway, I am bit stuck where it actually goes wrong. Does it work if you use `Access-Control-Allow-Origin`?

**Comment by axpro** [comment]
I wasn't attempting to set it as lowercase, symphony tests for a lowercase key [here](https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/class.frontendpage.php#L248).

The extension sets the key like this:

    [access-control-allow-origin: *] => Array (
        [header] => Access-Control-Allow-Origin: *
        [response_code] =>
    )

while the key set by symphony looks like this:

    [access-control-allow-origin] => Array (
        [header] => Access-Control-Allow-Origin:http://localhost
        [response_code] =>
    )

The extension should call:

    addHeaderToPage('Access-Control-Allow-Origin', '*');

but instead it calls:

    addHeaderToPage('Access-Control-Allow-Origin: *);

so the key ends up containing the value.

**Comment by michael-e** [comment]
Ah, my bad. Thanks for the explanation. I will care.

**Comment by axpro** [comment]
I would have done it myself but I'm not proficient in PHP. Thank you and happy new year!

**Comment by michael-e** [comment]
You found a very interesting (but stupid) bug here.

Do you think that people could live with a convention like "your string will be split at the first colon, the left side being the name and the right side being the value"?

(I am proposing this because the Symphony config does not support multi-dimensional arrays.)

**Comment by axpro** [comment]
I was thinking of the same solution. Maybe make the character configurable for future flexibility.

**Comment by michael-e** [comment]
I don't think it will ever need to be configurable. It can just be a convention.

I will push something today or tomorrow, just needs to be tested first. :-)

**Comment by axpro** [comment]
For the time being I managed to get it to work simply by puting two mapping in the config like so:

    'alloworiginfake' => 'Access-Control-Allow-Origin',

and

    'alloworigin' => 'Access-Control-Allow-Origin: *',

The first one sets the correct key needed by symphony and the second one gives the needed value.

**Comment by michael-e** [comment]
That is a very creative hack!

**Comment by michael-e** [comment]
I fixed it (hopefully).

**Comment by axpro** [comment]
Thank you

**Comment by michael-e** [comment]
You're welcome.
